package pt.ipg.projeto

import android.database.Cursor
import android.net.Uri
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.MenuItem
import android.view.View
import android.view.ViewGroup
import android.widget.SimpleCursorAdapter
import android.widget.Spinner
import android.widget.Toast
import androidx.loader.app.LoaderManager
import androidx.loader.content.CursorLoader
import androidx.loader.content.Loader
import androidx.navigation.fragment.findNavController
import com.google.android.material.snackbar.Snackbar
import pt.ipg.projeto.databinding.FragmentEditarModeloBinding


class EditarModeloFragment : Fragment(), LoaderManager.LoaderCallbacks<Cursor> {
    private var _binding: FragmentEditarModeloBinding? = null

    private val binding get() = _binding!!

    private var modelo: Modelo? = null

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        _binding = FragmentEditarModeloBinding.inflate(inflater, container, false)

        return binding.root
    }
    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val activity = requireActivity() as MainActivity
        activity.fragment = this
        activity.idMenuAtual = R.menu.menu_edicao

        if(arguments!= null) {
            modelo = editarModeloFragmentArgs.fromBundle(arguments!!).modelo

            if (modelo != null) {
                binding.editTextNomeModelo.setText(modelo!!.modelo)
                binding.editTextPrecoModelo.setText(modelo!!.preco)
            }
        }

        LoaderManager.getInstance(this).initLoader(ID_LOADER_MARCAS, null, this)

    }

    companion object {
        const val ID_LOADER_MARCAS = 0
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param id The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    override fun onCreateLoader(id: Int, args: Bundle?): Loader<Cursor>  =
        CursorLoader(
            requireContext(),
            ContentProviderCarros.ENDERECO_MARCAS,
            TabelaBDMarcas.TODAS_COLUNAS,
            null,
            null,
        "${TabelaBDMarcas.MARCAS}"
        )


    /**
     * Called when a previously created loader has finished its load.  Note
     * that normally an application is *not* allowed to commit fragment
     * transactions while in this call, since it can happen after an
     * activity's state is saved.  See [ FragmentManager.openTransaction()][androidx.fragment.app.FragmentManager.beginTransaction] for further discussion on this.
     *
     *
     * This function is guaranteed to be called prior to the release of
     * the last data that was supplied for this Loader.  At this point
     * you should remove all use of the old data (since it will be released
     * soon), but should not do your own release of the data since its Loader
     * owns it and will take care of that.  The Loader will take care of
     * management of its data so you don't have to.  In particular:
     *
     *
     *  *
     *
     *The Loader will monitor for changes to the data, and report
     * them to you through new calls here.  You should not monitor the
     * data yourself.  For example, if the data is a [android.database.Cursor]
     * and you place it in a [android.widget.CursorAdapter], use
     * the [android.widget.CursorAdapter.CursorAdapter] constructor *without* passing
     * in either [android.widget.CursorAdapter.FLAG_AUTO_REQUERY]
     * or [android.widget.CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER]
     * (that is, use 0 for the flags argument).  This prevents the CursorAdapter
     * from doing its own observing of the Cursor, which is not needed since
     * when a change happens you will get a new Cursor throw another call
     * here.
     *  *  The Loader will release the data once it knows the application
     * is no longer using it.  For example, if the data is
     * a [android.database.Cursor] from a [android.content.CursorLoader],
     * you should not call close() on it yourself.  If the Cursor is being placed in a
     * [android.widget.CursorAdapter], you should use the
     * [android.widget.CursorAdapter.swapCursor]
     * method so that the old Cursor is not closed.
     *
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that has finished.
     * @param data The data generated by the Loader.
     */
    override fun onLoadFinished(loader: Loader<Cursor>, data: Cursor?) {
        val adapterMarcas = SimpleCursorAdapter(
            requireContext(),
            android.R.layout.simple_list_item_1,
            data,
            arrayOf(TabelaBDMarcas.MARCAS),
            intArrayOf(android.R.id.text1),
            0
        )

        binding.spinnerMarca.adapter = adapterMarcas

        atualizaMarcasSelecionada()

    }

    private fun atualizaMarcasSelecionada() {
        if (modelo == null)return
        val idMarca = modelo!!.marca.id

        val ultimaMarca = binding.spinnerMarca.count - 1

        for (i in 0..ultimaMarca){
            if(binding.spinnerMarca.getItemIdAtPosition(i) == idMarca){
                binding.spinnerMarca.setSelection(i)
                return
            }
        }


    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     *
     *
     * This will always be called from the process's main thread.
     *
     * @param loader The Loader that is being reset.
     */
    override fun onLoaderReset(loader: Loader<Cursor>) {
        if(_binding == null)return
        binding.spinnerMarca.adapter = null
    }

    fun processaOpcaoMenu(item: MenuItem) : Boolean =
        when(item.itemId) {
            R.id.action_guardar -> {
                guardar()
                true
            }
            R.id.action_cancelar -> {
                voltaListaLivros()
                true
            }
            else -> false
        }

    private fun guardar() {
        val modelo = binding.editTextNomeModelo.text.toString()
        if(modelo.isBlank()){
            binding.editTextNomeModelo.error = getString(R.string.modelo_obrigatorio)
            binding.editTextNomeModelo.requestFocus()
            return
        }

        val idMarca = binding.spinnerMarca.selectedItemId
        if(idMarca == Spinner.INVALID_ROW_ID){
            binding.textViewMarcaNome.error = getString(R.string.marca_obrigatoria)
            binding.spinnerMarca.requestFocus()
            return
        }

        val preco = binding.editTextPrecoModelo.text.toString().toDouble()
        if(preco == null){
            binding.editTextPrecoModelo.error = getString(R.string.preco_obrigatorio)
            binding.editTextPrecoModelo.requestFocus()
            return
        }

        val modeloGuardado = alteraModelo(modelo, idMarca, preco)

        if (modeloGuardado){
            Toast.makeText(requireContext(), R.string.modelo_guardado_sucesso, Toast.LENGTH_LONG)
                .show()
            voltaListaLivros()
        }else{
            Snackbar.make(binding.editTextNomeModelo, R.string.erro_guardar_modelo, Snackbar.LENGTH_INDEFINITE ).show()
            return
        }



    }

    private fun alteraModelo(modelo: String, idMarca: Long, preco: Double): Boolean {
        val modelo = Modelo(modelo, Marca(id = idMarca), preco)

        val enderecoModelo = Uri.withAppendedPath(ContentProviderCarros.ENDERECO_MODELOS, "${this.modelo!!.id}")

        val registosAlterados = requireActivity().contentResolver.update(enderecoModelo, modelo.toContentValues(), null, null)

        return registosAlterados == 1
    }

    private fun voltaListaLivros() {
       findNavController().navigate(R.id.action_editarModeloFragment_to_listaModelosfragment)
    }


}